export namespace Flag {
  export const FLOCKS_AUTO_SHARE = truthy("FLOCKS_AUTO_SHARE")
  export const FLOCKS_GIT_BASH_PATH = process.env["FLOCKS_GIT_BASH_PATH"]
  export const FLOCKS_CONFIG = process.env["FLOCKS_CONFIG"]
  export const FLOCKS_CONFIG_DIR = process.env["FLOCKS_CONFIG_DIR"]
  export const FLOCKS_CONFIG_CONTENT = process.env["FLOCKS_CONFIG_CONTENT"]
  export const FLOCKS_DISABLE_AUTOUPDATE = truthy("FLOCKS_DISABLE_AUTOUPDATE")
  export const FLOCKS_DISABLE_PRUNE = truthy("FLOCKS_DISABLE_PRUNE")
  export const FLOCKS_DISABLE_TERMINAL_TITLE = truthy("FLOCKS_DISABLE_TERMINAL_TITLE")
  export const FLOCKS_PERMISSION = process.env["FLOCKS_PERMISSION"]
  export const FLOCKS_DISABLE_DEFAULT_PLUGINS = truthy("FLOCKS_DISABLE_DEFAULT_PLUGINS")
  export const FLOCKS_DISABLE_LSP_DOWNLOAD = truthy("FLOCKS_DISABLE_LSP_DOWNLOAD")
  export const FLOCKS_ENABLE_EXPERIMENTAL_MODELS = truthy("FLOCKS_ENABLE_EXPERIMENTAL_MODELS")
  export const FLOCKS_DISABLE_AUTOCOMPACT = truthy("FLOCKS_DISABLE_AUTOCOMPACT")
  export const FLOCKS_DISABLE_MODELS_FETCH = truthy("FLOCKS_DISABLE_MODELS_FETCH")
  export const FLOCKS_DISABLE_CLAUDE_CODE = truthy("FLOCKS_DISABLE_CLAUDE_CODE")
  export const FLOCKS_DISABLE_CLAUDE_CODE_PROMPT =
    FLOCKS_DISABLE_CLAUDE_CODE || truthy("FLOCKS_DISABLE_CLAUDE_CODE_PROMPT")
  export const FLOCKS_DISABLE_CLAUDE_CODE_SKILLS =
    FLOCKS_DISABLE_CLAUDE_CODE || truthy("FLOCKS_DISABLE_CLAUDE_CODE_SKILLS")
  export const FLOCKS_FAKE_VCS = process.env["FLOCKS_FAKE_VCS"]
  export const FLOCKS_CLIENT = process.env["FLOCKS_CLIENT"] ?? "cli"
  export const FLOCKS_SERVER_PASSWORD = process.env["FLOCKS_SERVER_PASSWORD"]
  export const FLOCKS_SERVER_USERNAME = process.env["FLOCKS_SERVER_USERNAME"]

  // Experimental
  export const FLOCKS_EXPERIMENTAL = truthy("FLOCKS_EXPERIMENTAL")
  export const FLOCKS_EXPERIMENTAL_FILEWATCHER = truthy("FLOCKS_EXPERIMENTAL_FILEWATCHER")
  export const FLOCKS_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("FLOCKS_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const FLOCKS_EXPERIMENTAL_ICON_DISCOVERY =
    FLOCKS_EXPERIMENTAL || truthy("FLOCKS_EXPERIMENTAL_ICON_DISCOVERY")
  export const FLOCKS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy("FLOCKS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const FLOCKS_ENABLE_EXA =
    truthy("FLOCKS_ENABLE_EXA") || FLOCKS_EXPERIMENTAL || truthy("FLOCKS_EXPERIMENTAL_EXA")
  export const FLOCKS_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = number("FLOCKS_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
  export const FLOCKS_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("FLOCKS_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const FLOCKS_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("FLOCKS_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const FLOCKS_EXPERIMENTAL_OXFMT = FLOCKS_EXPERIMENTAL || truthy("FLOCKS_EXPERIMENTAL_OXFMT")
  export const FLOCKS_EXPERIMENTAL_LSP_TY = truthy("FLOCKS_EXPERIMENTAL_LSP_TY")
  export const FLOCKS_EXPERIMENTAL_LSP_TOOL = FLOCKS_EXPERIMENTAL || truthy("FLOCKS_EXPERIMENTAL_LSP_TOOL")
  export const FLOCKS_EXPERIMENTAL_PLAN_MODE = FLOCKS_EXPERIMENTAL || truthy("FLOCKS_EXPERIMENTAL_PLAN_MODE")

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}
